es6-arrow-functions - Marshall Vogt
marshall-vogt/c0723-code-solutions pull request #77
Opened 2023-08-21 21:03 UTC by marshall-vogt

![Screenshot 2023-08-21 at 1 37 11 PM](https://github.com/marshall-vogt/c0723-code-solutions/assets/131848819/5a02641c-8c6a-456c-bec1-1fd09d981007)

2023-08-21 21:19 UTC, marshall-vogt commented
![Screenshot 2023-08-21 at 1 37 11 PM](https://github.com/marshall-vogt/c0723-code-solutions/assets/131848819/3f109eea-70e1-49b3-9e77-f036694f00bc)

2023-08-22 16:49 UTC, shawnkost requested changes
One change here Marshall

2023-08-22 16:49 UTC, shawnkost commented on es6-arrow-functions/main.js
> +}
This should become an arrow function

2023-08-22 17:09 UTC, shawnkost approved these changes
👍🏻

2023-08-22 17:38 UTC, merged